### ISSUE TITLE
Domain not verifing automatically on android

### ISSUE THREAD

**Issue by MalikHamza007** [Saqib92/cap-deeplink-issue#1]

**Comment by Saqib92** [comment]
report it to capacitor team..

**Comment by MalikHamza007** [comment]
> report it to capacitor team..

i mean after applying the intent filter and assetlinks.json but still it navigates to my website and says 404 not found

but only from android 12 and above

**Comment by Saqib92** [comment]
Check Documentation:
https://capacitorjs.com/docs/guides/deep-links


Verify that your assets link is correctly setup:
https://developers.google.com/digital-asset-links/tools/generator

**Comment by MalikHamza007** [comment]
> Check Documentation: https://capacitorjs.com/docs/guides/deep-links
> 
> Verify that your assets link is correctly setup: https://developers.google.com/digital-asset-links/tools/generator

I have read so much docs on this the android docs , capacitor even the asset links setup.
but yeah even after every thing is double verified i'll take a look again.

**Comment by mumair4462** [comment]
@Saqib92 

I hope you’re doing well.

I recently visited your website, https://codingchefs.com/, and noticed an error that might impact the user experience. I’d be happy to connect with you on LinkedIn to share the details and help address the issue if needed.

Feel free to reach out to me at your convenience.

My Linkedin profile: https://www.linkedin.com/in/umairsaeed4462/

**Comment by Saqib92** [comment]
> @Saqib92
> 
> I hope you’re doing well.
> 
> I recently visited your website, https://codingchefs.com/, and noticed an error that might impact the user experience. I’d be happy to connect with you on LinkedIn to share the details and help address the issue if needed.
> 
> Feel free to reach out to me at your convenience.
> 
> My Linkedin profile: https://www.linkedin.com/in/umairsaeed4462/

Message me on discord: saqibkhan92
